### ISSUE TITLE
Ovirt - orphaned cleanup null pointer

### ISSUE THREAD

**Issue by TaLoN1x** [bl4ko/netbox-ssot#126]
I get this error

2024/05/03 05:41:10 INFO    (main): Cleaning up orphaned objects...
panic: assignment to entry in nil map

goroutine 19 [running]:
github.com/bl4ko/netbox-ssot/internal/netbox/inventory.(*NetboxInventory).AddVM(0xc0000de1e0, {0xf3b8b8, 0xc0008be120}, 0xc0013d0540)
        C:/BIT/New folder/netbox-ssot/internal/netbox/inventory/add_items.go:761 +0x6dd
github.com/bl4ko/netbox-ssot/internal/source/ovirt.(*OVirtSource).syncVms(0xc00008c820, 0xc0000de1e0)
        C:/BIT/New folder/netbox-ssot/internal/source/ovirt/ovirt_sync.go:638 +0xe5
github.com/bl4ko/netbox-ssot/internal/source/ovirt.(*OVirtSource).Sync(0xc00008c820, 0xc0000de1e0)
        C:/BIT/New folder/netbox-ssot/internal/source/ovirt/ovirt.go:107 +0x2fb
main.main.func1({0xf3b8b8, 0xc0008be120}, {0xf39b48, 0xc00008c820})
        C:/BIT/New folder/netbox-ssot/cmd/netbox-ssot/main.go:98 +0x2f1
created by main.main in goroutine 1
        C:/BIT/New folder/netbox-ssot/cmd/netbox-ssot/main.go:78 +0x67e

**Comment by bl4ko** [comment]
Oh i see, this was introduced in latest version, will fix.

**Comment by bl4ko** [comment]
@TaLoN1x it should work now?

**Comment by TaLoN1x** [comment]
yes, 0.6.5 works good!
