### ISSUE TITLE
linked vcenter null pointer

### ISSUE THREAD

**Issue by TaLoN1x** [bl4ko/netbox-ssot#128]
I get a nullpointer exception on linked vcenter import. Looks like code cannot handle clusters with no vswitches :)

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x170 pc=0xa53c88]

goroutine 24 [running]:
github.com/bl4ko/netbox-ssot/internal/source/vmware.(*VmwareSource).InitHosts(0xc000b3c0f0, {0xf3b910, 0xc0009d9720}, 0xc000ab5a90)
        /Users/jurikononov/src/netbox-ssot/internal/source/vmware/vmware_init.go:140 +0x448
github.com/bl4ko/netbox-ssot/internal/source/vmware.(*VmwareSource).Init(0xc000b3c0f0)
        /Users/jurikononov/src/netbox-ssot/internal/source/vmware/vmware.go:175 +0x1439
main.main.func1({0xf3b8d8, 0xc000b01890}, {0xf39b90, 0xc000b3c0f0})
        /Users/jurikononov/src/netbox-ssot/cmd/netbox-ssot/main.go:87 +0x154
created by main.main in goroutine 1
        /Users/jurikononov/src/netbox-ssot/cmd/netbox-ssot/main.go:78 +0x67e

**Comment by bl4ko** [comment]
Thanks, will look into it

**Comment by bl4ko** [comment]
@TaLoN1x since I can't test this locally (can't reproduce on my vcenter, because I have only read only access), could you test develop branch?

**Comment by TaLoN1x** [comment]
develop brunch works good. with this
