### ISSUE TITLE
vcenter untagged vlan

### ISSUE THREAD

**Issue by TaLoN1x** [bl4ko/netbox-ssot#129]
in vcenter vlan with vid == 0 whould be ignored (untagged, aka native).

**Comment by bl4ko** [comment]
Hmm, could you provide some additional context? Currenly `vid 0` is ignored because of [omitempty](https://github.com/bl4ko/netbox-ssot/blob/6b5a477db9232486f896829ebd84759411765069/internal/netbox/objects/ipam.go#L99).

**Comment by TaLoN1x** [comment]
vid is mandatory field in netbox API

**Comment by bl4ko** [comment]
Yes I know, but you can't add vlan with vid 0 to netbox

**Comment by TaLoN1x** [comment]
Correct, but technically you can have it in vcenter and or ovirt. So its better not to try and push it to Netbox (current behavor), but throw warning and ignore it.

**Comment by TaLoN1x** [comment]
Currentry in this case i gey error that vid value is mandatory and import halts.

**Comment by bl4ko** [comment]
Ok, I guess this is related to #85. Could you additionally provide some log so I can see where this problem occurs, I will try to filter out all vlans with tag 0.

**Comment by TaLoN1x** [comment]
I will try to reproduce it on Monday and send you logs, thus I temporarily worked that around like this:
vmware_sync.go:31
"if len(dvpg.VlanIDs) == 1 && len(dvpg.VlanIDRanges) == 0 {" -> "if len(dvpg.VlanIDs) == 1 && len(dvpg.VlanIDRanges) == 0 && dvpg.VlanIDs[0] != 0 {"
