### ISSUE TITLE
Manufacturers and device types

### ISSUE THREAD

**Issue by TaLoN1x** [bl4ko/netbox-ssot#142]
The manufacturers should use official taxonomy as per https://github.com/netbox-community/devicetype-library

Thus I do understand that different Tools and APIs might give different representations, maybe having a mathing table or simmilar?

i.e.
Cisco Systems Inc. -> Cisco
Fortinet. Inc. -> Fortinet
Fortinet Inc. -> Fortinet
HP -> HPE
HP Enterprise -> HPE
HP Inc. -> HPE
and so on

**Comment by bl4ko** [comment]
Yes this is currently missing, but it is a main goal to include device type library in this microservice, because it will be also useful to fetch all data from library for physical devices (interfaces etc.). Will soon start working on it.

The idea is to dynamically generate static code (golang map) with [go generate](https://go.dev/blog/generate). So on every build there will be map of all data created from devicetype-library.

**Comment by TaLoN1x** [comment]
sound like a good plan.
P.S. I soon will create another issue related to deviced and virtual appliances that would impact plan you described a bit.

**Comment by TaLoN1x** [comment]
solution also should not create device templates on it's own if there is an existing template in the system or in the device-type library. Often there is more of valuable information such as weight, size, etc. that is essential for other functions like DCIM.

**Comment by bl4ko** [comment]
I will come with a plan in a few days and we can talk more about implementation...

**Comment by bl4ko** [comment]
Have automatically generated (data.go)[https://raw.githubusercontent.com/bl4ko/netbox-ssot/142-manufacturers-and-device-types/internal/devices/data.go] from netbox's device library, just have to figure out how to include this in external sourcese.

**Comment by bl4ko** [comment]
Hello I have written generator which creates static [device data map](https://github.com/bl4ko/netbox-ssot/blob/82141c617c4915bafe6fbea2be11888402411b7c/internal/devices/combined_data.go#L4) from [devicetype-library](https://github.com/netbox-community/devicetype-library). This data is then used to get correct slug for device types. Also other physical aspects for each device can be added easily in the future.

For manufacturer map, as you suggested I have created special [serialize function](https://github.com/bl4ko/netbox-ssot/blob/82141c617c4915bafe6fbea2be11888402411b7c/internal/utils/utils.go#L249).
