### ISSUE TITLE
Asset tag vs source-id

### ISSUE THREAD

**Issue by TaLoN1x** [bl4ko/netbox-ssot#147]
I see that currently solution uses asset tag as field to store UID/GUID from the reference system. The Asset tag field is essential for inventory numbers / ERP related tag for the DCIM functionality of the Netbox, therefore I would suggest to migrate this to the source-id custom field. I think source-id is already being used for some objects, so it just need unification?

**Comment by bl4ko** [comment]
Hello, currently the terms are used in the following way:

- source-id custom field is currently used to store object's id on the source, for example:

  - ovirt: every object has an "id" field, this "id" field from ovirt api is then mapped to source-id custom field in netbox

- asset tag is currently mapped from uuid from the host devices to the netbox asset tag field
  - ovirt: every host has an "uuid" attribute, so this uuid attribute is mapped to netbox asset tag

**Comment by TaLoN1x** [comment]
but then you can also specify a real asset-tag (that companies use in their inventory) in most hypervisors also and current behaviour conflicts with ability to use this data in relation to a device.

**Comment by bl4ko** [comment]
Yes I agree, I will fix this behaviour.
