### ISSUE TITLE
Soft delete and changelog

### ISSUE THREAD

**Issue by TaLoN1x** [bl4ko/netbox-ssot#148]
In the CMDB/IPAN/DCIM one of the essential roles is to have historical information on what was the object state and why at the point of time. Therefore I think there should be a soft delete option for objects that are either currently not observed of have been deleted, otherwise the whole history (changelog) is lost together with the record.

**Comment by bl4ko** [comment]
Yes its good to have history of an object, but how would you implement this in netbox? There is no soft delete option, when an objects gets deleted from the API all changelog gets lost with it.

**Comment by TaLoN1x** [comment]
I'd say playing with the status of an object or assigning a tag would be a solution. I will think of it and describe my vision

**Comment by kirkkak** [comment]
Lifecycle wise i imagine:
asset -> purchase/inventory id/stocking can be handled in Inventory plugin/module
resource -> in use/on the field in core netbox [as device]

Nevertheless device-asset (even in case of reimage .. new uuid; rename etc) relationship and/or device should not be deleted as it is "same thing" with different values or..?

**Comment by bl4ko** [comment]
The easiest way I currently see, is to add **orphan tag** to objects which would mark soft deletion. But this approach would introduce use to new issues like:

- which orphans to autodelete and which to keep
- adding new objects whose primary keys would overlap with orphans would trigger error

So full redesign of OrphanManager will also have to be implemented.

**Comment by n-rodriguez** [comment]
> The easiest way I currently see, is to add **orphan tag** to objects which would mark soft deletion.

Hi there! This is how https://github.com/bb-Ricardo/netbox-sync works and it works pretty well :)

See: https://github.com/bb-Ricardo/netbox-sync?tab=readme-ov-file#principles or https://github.com/bb-Ricardo/netbox-sync?tab=readme-ov-file#pruning

**Comment by bl4ko** [comment]
Hello thanks for the resources. I think the idea here is, if user specifies

```yaml
netbox.removeOrphans: False
```

Then all objects that are orphans should be given **Orphan** tag. And on the next run if they are found this tag is deleted. 
Also if removeOrphans is **False**, user can specify value that determines how long do we keep orphans (default will be forever):
 - `netbox.OrphanLifeSpan: 3` which would mean remove orhpans after 3 days
 
 Would this approach be the right one?

**Comment by n-rodriguez** [comment]
> Hello thanks for the resources. I think the idea here is, if user specifies
> 
> ```yaml
> netbox.removeOrphans: False
> ```
> 
> Then all objects that are orphans should be given **Orphan** tag

I think you mean :

```yaml
netbox.removeOrphans: True
```

right?
