### ISSUE TITLE
1.0 breaks v3 support and panics

### ISSUE THREAD

**Issue by TaLoN1x** [bl4ko/netbox-ssot#153]
Running SSOT 1.0 against Netbox 3.7.8 panics:

panic: reflect: slice index out of range

goroutine 1 [running]:
reflect.Value.Index({0xb2c040?, 0xc00037a438?, 0x4a2275?}, 0xad2bd8?)
        /usr/local/Cellar/go/1.22.2/libexec/src/reflect/value.go:1430 +0x167
github.com/bl4ko/netbox-ssot/internal/utils.convertSliceToComparableSlice({0xb2c040?, 0xc00037a438?, 0x197?})
        /Users/jurikononov/src/tmp/netbox-ssot/internal/utils/diff_map.go:243 +0x46
github.com/bl4ko/netbox-ssot/internal/utils.addSliceDiff({0xb2c040?, 0xc00036d498?, 0x1?}, {0xb2c040?, 0xc00037a438?, 0xad2bd2?}, {0xad2bd8, 0xc}, 0x58?, 0xc000324b70)
        /Users/jurikononov/src/tmp/netbox-ssot/internal/utils/diff_map.go:219 +0x22a
github.com/bl4ko/netbox-ssot/internal/utils.JSONDiffMapExceptID({0xb8f1e0, 0xc00036d450}, {0xb8f1e0, 0xc00037a3f0}, 0x0, 0xc00015fef0)
        /Users/jurikononov/src/tmp/netbox-ssot/internal/utils/diff_map.go:166 +0x985
github.com/bl4ko/netbox-ssot/internal/netbox/inventory.(*NetboxInventory).AddCustomField(0xc0000dc1e0, {0xf3c378, 0xc00015fec0}, 0xc00036d450)
        /Users/jurikononov/src/tmp/netbox-ssot/internal/netbox/inventory/add_items.go:259 +0x145
github.com/bl4ko/netbox-ssot/internal/netbox/inventory.(*NetboxInventory).InitSsotCustomFields(0xc0000dc1e0, {0xf3c378, 0xc00015fec0})
        /Users/jurikononov/src/tmp/netbox-ssot/internal/netbox/inventory/init_items.go:343 +0x199
github.com/bl4ko/netbox-ssot/internal/netbox/inventory.(*NetboxInventory).Init(0xc0000dc1e0)
        /Users/jurikononov/src/tmp/netbox-ssot/internal/netbox/inventory/inventory.go:217 +0xb9d
main.main()
        /Users/jurikononov/src/tmp/netbox-ssot/cmd/netbox-ssot/main.go:51 +0x532

Ideally it should check API version and return error that API is unsupported or so :)

**Comment by bl4ko** [comment]
Hello, this is because netbox introduced breaking changes in v4, info has been added to [readme](https://github.com/bl4ko/netbox-ssot?tab=readme-ov-file#netbox-ssot), I will also add api version check in code as you suggested.
