### ISSUE TITLE
No VM network interfaces from one of proxmox nodes

### ISSUE THREAD

**Issue by lemeshovich** [bl4ko/netbox-ssot#235]
Hello, im facing an issue. My proxmox is running in a cluster with few IPs. In the proxmox i have two nodes each with a certain number of VMs. I configured your netbox-ssot's source to one of the proxmox's cluster IPs. And in that case after **docker run**, VM's inventory from one of proxmox nodes seems to have a correct data, unlike VMs from another node, which have no interfaces at all:

<details>
  <summary>No VM's interfaces from one node</summary>
  <p>
    <img src="https://github.com/user-attachments/assets/cf54e9f9-5c88-4221-bae2-28fda436ea00">
  </p>
</details>
<details>
  <summary>VM's interfaces from another node is OK</summary>
  <p>
    <img src="https://github.com/user-attachments/assets/38df37ca-3fdd-469b-86d8-44f4a0cf0e14">
  </p>
</details>

If i change netbox-ssot's source to another proxmox IP from the cluster, then the situation changes exactly the opposite. VM's interfaces from a node where they were missing, they appear. And VM's interfaces from a node where they were present, they disappear.

Current workaround i found is to add few source configs for each proxmox cluster IP,  in that case all VM's interfaces seems OK. But i don't think it's a great solution. Any ideas?

**Comment by bl4ko** [comment]
Hello thanks for reporting this, this is indeed a bug
