### ISSUE TITLE
Incorrect link-local IPv6 addresses with zone index processing

### ISSUE THREAD

**Issue by lemeshovich** [bl4ko/netbox-ssot#304]
When configuring `ignoredSubnets` I specified `::/0` to exclude all IPv6 addresses from synchronization. However, link-local addresses with a zone index (e.g., fe80::2744:6e22:ce45:c4b3%27/64) still attempt to sync and trigger warnings:
```
2024/10/29 10:41:35 WARNING (proxmox): failed adding ip address IPAddress{ID: 0, Address: fe80::2744:6e22:ce45:c4b3%27/64, Status: active, DNSName: } with: unexpected status code: 500: {"error": "'data'", "exception": "KeyError", "netbox_version": "4.0.8", "python_version": "3.11.6"}
```
The presence of the zone index (e.g., %27) seems to prevent these addresses from being correctly filtered out. Could you please update the handling of IPv6 addresses with zone indices to ensure they are properly ignored according to `ignoredSubnets` configuration? This would prevent such addresses from being sent to NetBox and avoid the related warnings.

**Comment by bl4ko** [comment]
Thanks, thats a great find. I will fix it

**Comment by lemeshovich** [comment]
no warnings for now, great, thanks!
