### ISSUE TITLE
Interface Filter not working on Fortigate

### ISSUE THREAD

**Issue by jmcguir** [bl4ko/netbox-ssot#331]
As far as I can tell the fortigate source doesn't respect the interface filter section of the config. 

It doesn't ever call in fortigate.sync when it's iterating through interfaces:

		if utils.FilterInterfaceName(iface.Name, pas.SourceConfig.InterfaceFilter) {
			pas.Logger.Debugf(pas.Ctx, "interface %s is filtered out with interface filter %s", iface.Name, pas.SourceConfig.InterfaceFilter)
			continue

If the change is this simple, I can make it but I don't really know go so I'm not exactly confident this will fix it.

**Comment by bl4ko** [comment]
Thanks, you are right, the interface filtering functionality is missing in the fortigate source. The code you have provided should make it work :)
