### ISSUE TITLE
[Feature Request] Implement permitted_subnets

### ISSUE THREAD

**Issue by n-rodriguez** [bl4ko/netbox-ssot#356]
### What is the feature?

Hi there! `netbox-ssot` already provides `source.ignoredSubnets` but it would be nice to also have `source.permittedSubnets` like in `netbox-sync` : `permitted_subnets = 10.3.8.0/23`

### Why is this feature important?

Sometimes it's easier to configure `permittedSubnets` than `ignoredSubnets`. Thank you!

**Comment by bl4ko** [comment]
Yeah, I agree. Will implement this
